### ISSUE TITLE
End of cruise notification

### ISSUE THREAD

**Issue by egruebel** [webbpinner/OpenVDMv2#19]
Requesting a home page warning when the System Status is on (cruise collection running) but the specified cruise end date has passed.

**Comment by webbpinner** [comment]
...a little background on this request.
Recently OpenVDM suddenly stopped pulling files from remote collection systems to the Data Warehouse mid-cruise.  There were no errors reported and no other indications of system, software or networking problems.

What happened was that when the cruise was created in OpenVDM a start and an end date were defined.  For unforeseen reasons the cruise was exteneded by a day.  This change in the cruise schedule was not relayed into OpenVDM.  When the clock reached the point in time when OpenVDM was told the cruise was over the system stopped pulling in new files.

OpenVDM worked exactly as it had been instructed to however Erich is absolutely correct that there should be some visual indication of this so not to confuse operators.

After discussing possible option with Erich via Slack the plan is to change the color of the System Status Panel to Yellow and include a message explaining that OpenVDM is not copying files because it thinks either the cruise hasn't started or that the cruise has finished.

**Comment by webbpinner** [comment]
Implemented in v2.4
